language: android
android:
  components:
    - build-tools-25.0.0
    - android-25
    - android-L
    - sys-img-armeabi-v7a-android-tv-l
    - add-on
    - extra
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
